
#기본 설정

security:
  oauth2:
    authorization:
      token-key-access: isAuthenticated()
    resource:      jwt:        key-value: hrpj@123
        #token expire 값은 시간으로 입력
        access-token-expire: 2
        refresh-token-expire: 720

logging.level:
  org.springframework:
    security: info
    boot: info
    
---
#local 설정
server:
  port: 8082
  
spring:
  profiles: local
  
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true

  datasource:
    oauth:
      url: jdbc:mariadb://192.168.20.66:3306/oauth?autoReconnect=true
      driver-class-name: org.mariadb.jdbc.Driver
      username: oauth
      password: oauth@123
      max-idle: 10
      max-active: 20
      max-wait: -1
      validation-query: SELECT 1
      test-on-borrow: true
    rest:
      url: jdbc:mariadb://192.168.20.66:3306/hrpj?autoReconnect=true
      driver-class-name: org.mariadb.jdbc.Driver
      username: hrpj
      password: hrpj@123
      max-idle: 10
      max-active: 20
      max-wait: -1
      validation-query: SELECT 1
      test-on-borrow: true
    
---
#local Home 설정
server:
  port: 8082
  
spring:
  profiles: localhome
  
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true

  datasource:
    oauth:
      url: jdbc:mariadb://localhost:3306/oauth?autoReconnect=true
      driver-class-name: org.mariadb.jdbc.Driver
      username: oauth
      password: oauth@123
      max-idle: 10
      max-active: 20
      max-wait: -1
      validation-query: SELECT 1
      test-on-borrow: true
    rest:
      url: jdbc:mariadb://localhost:3306/hrpj?autoReconnect=true
      driver-class-name: org.mariadb.jdbc.Driver
      username: hrpj
      password: hrpj@123
      max-idle: 10
      max-active: 20
      max-wait: -1
      validation-query: SELECT 1
      test-on-borrow: true

---
#dev 설정
server:
  port: 8082
  
spring:
  profiles: dev
  
---
#product 설정
server:
  port: 8082
  
spring:
  profiles: prod
  
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true

  datasource:
    oauth:
      url: jdbc:mariadb://121.126.223.222:3306/oauth?autoReconnect=true
      driver-class-name: org.mariadb.jdbc.Driver
      username: oauth
      password: oauth@123
      max-idle: 10
      max-active: 20
      max-wait: -1
      validation-query: SELECT 1
      test-on-borrow: true
    rest:
      url: jdbc:mariadb://121.126.223.222:3306/hrpj?autoReconnect=true
      driver-class-name: org.mariadb.jdbc.Driver
      username: hrpj
      password: hrpj@123
      max-idle: 10
      max-active: 20
      max-wait: -1
      validation-query: SELECT 1
      test-on-borrow: true
      
logging:
  config: classpath:logback-spring.xml